# https://terraform-docs.io/user-guide/configuration/

settings:
  hide-empty: true

formatter: "md"

recursive:
  enabled: true
  path: components/dcr

sections:
  show-all: true

output:
  file: README.md
