# https://terraform-docs.io/user-guide/configuration/

settings:
  hide-empty: true

formatter: "markdown table"

sections:
  show:
    - requirements
    - inputs
    - outputs
    - resources

output:
  file: README.md
